{{- if not .Values.envSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightrag.envSecretName" . }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.envSecret.secretKey }}: |-
    {{- include "lightrag.envContent" . | nindent 4 }}
{{- end }}
