{{- if .Values.serviceAccount.create }}
{{- $annotations := dict -}}
{{- range $key, $val := (default (dict) .Values.commonAnnotations) -}}
{{- $_ := set $annotations $key $val -}}
{{- end -}}
{{- range $key, $val := (default (dict) .Values.serviceAccount.annotations) -}}
{{- $_ := set $annotations $key $val -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lightrag.serviceAccountName" . }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
{{- end }}
