apiVersion: v2
name: lightrag
description: A Helm chart for LightRAG, an efficient and lightweight RAG system
type: application
version: 0.2.0
appVersion: "v1.4.10"
maintainers:
  - name: LightRAG Team
  - name: earayu
    email: earayu@gmail.com
